version: '3.5'

services:

  broker:
    image: eclipse-mosquitto
    networks:
      - net
    expose:
      - "1883"
      - "8883"
      - "9001"
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/ca_certificates/:/etc/mosquitto/ca_certificates/
      - ./mosquitto/certs/:/etc/mosquitto/certs/


  server:
    image: quarkus/iot-server-jvm
#    image: payara/iot-server-jvm
    networks:
      - net
    environment:
      - mqtt.broker.protocol=ssl
      - mqtt.broker.host=broker
      - mqtt.broker.port=8883
      - mqtt.broker.topic=data
      - quarkus.http.ssl.certificate.key-store-file=/opt/bigfinite/certs/server.keystore.jks
      - quarkus.http.ssl.certificate.key-store-password=bigfinite
      - quarkus.http.ssl.certificate.key-store-file-type=JKS
      - cert.cert-authority=/opt/bigfinite/certs/ca.crt
      - cert.public-key=/opt/bigfinite/certs/server.crt
      - cert.private-key=/opt/bigfinite/certs/server.key
      - cert.password=bigfinite
    ports:
      - 9081:9081
      - 8443:8443
    depends_on:
      - broker
    

  client:
    image: quarkus/iot-client-jvm
    networks:
      - net
    environment:
      - mqtt.broker.protocol=ssl
      - mqtt.broker.host=broker
      - mqtt.broker.port=8883
      - mqtt.broker.topic=data
      - server.base.url=https://server:8443
      - cert.public-key=/opt/bigfinite/certs/client.crt
      - cert.private-key=/opt/bigfinite/certs/client.key
      - cert.password=bigfinite
    ports:
      - 9080:9080
    depends_on:
      - broker
      - server


networks:
  net:
